CREATE DATABASE IF NOT EXISTS product_app CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE product_app;
CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    type ENUM('DVD', 'Book', 'Furniture') NOT NULL,
    size INT DEFAULT NULL,
    weight FLOAT DEFAULT NULL,
    height FLOAT DEFAULT NULL,
    width FLOAT DEFAULT NULL,
    length FLOAT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
